apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-openai-chat
  labels:
    app: azure-openai-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azure-openai-chat
  template:
    metadata:
      labels:
        app: azure-openai-chat
    spec:
      containers:
      - name: azure-openai-chat
        image: aksdemoacr.azurecr.io/azure-openai-chat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: azure-openai-secrets
              key: api-key
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: azure-openai-secrets
              key: endpoint
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
