apiVersion: v1
kind: Service
metadata:
  name: azure-openai-chat
  labels:
    app: azure-openai-chat
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: azure-openai-chat